version: '3.8'

services:
  capsule-node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: capsule-blockchain
    restart: unless-stopped
    ports:
      - "26656:26656"  # P2P port
      - "26657:26657"  # RPC port
      - "1317:1317"    # REST API port
      - "9090:9090"    # gRPC port
    volumes:
      - capsule_data:/root/.simd
      - ./docker/init.sh:/usr/local/bin/init.sh:ro
    environment:
      - CHAIN_ID=capsule-testnet-1
      - MONIKER=capsule-validator
      - KEYRING_BACKEND=test
    command: >
      sh -c "
        if [ ! -f /root/.simd/config/genesis.json ]; then
          echo 'Initializing new blockchain node...'
          /usr/local/bin/init.sh
        else
          echo 'Starting existing blockchain node...'
        fi
        simd start --minimum-gas-prices=0.0001stake
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:26657/status"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Optional: Add monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: capsule-prometheus
    restart: unless-stopped
    ports:
      - "9091:9090"
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    depends_on:
      - capsule-node
    profiles: ["monitoring"]

volumes:
  capsule_data:
    driver: local
  prometheus_data:
    driver: local

networks:
  default:
    name: capsule-network
